### ISSUE TITLE
Create client accounts

### ISSUE THREAD

**Issue by gokul50** [xmppjs/xmpp.js#908] opened 2021-08-11 05:55 UTC
Is there any way to create a new client account in openfire server via this library? Iam new to this library so I don't know much more about that's why. Can anyone please help me out in this?

And can we create groups and send messages to group members using this library ?

**Comment by sonnyp** [comment] 2021-08-19 18:27
Duplicate of https://github.com/xmppjs/xmpp.js/issues/783

There is an issue template for a reason.

> ⚠ If you need help with XMPP itself, please visit https://xmpp.org/community/ instead.

**Closed by sonnyp** 2021-08-19 18:27 UTC
