### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by tijszwinkels** [xmppjs/xmpp.js#546] opened 2018-07-14 07:25 UTC
I'm using xmpp.js to connect directly to an XMPP server socket (xmpp://<url>:5222). I haven't tried any other connection methods, but I suspect this issue might surface there as well.

I have an application that receives some volume of pubsub messages, and I noticed a memory-leak in xmpp.js

It seems that the library retains every single stanza that was received.

If I modify the demo-client from: http://xmppjs.org/client/ like so:

```
client.on('stanza', stanza => {
  console.log(stanza.parent.toString());
})
``` 

This parent contains every XMPP stanza that was sent. This shows that this data is retained in memory.

Similarly, if I modify the client like so:

```
client.on('stanza', stanza => {
    stanza.parent.children = []; // Terrible hack to prevent memory-leak.
})
```

The memory-leak goes away.

**Comment by robertklep** [comment] 2018-08-22 15:10
I'm using this module as part of an app running on a resource-constrained device. I previously used `node-xmpp-client`, but moving to `xmpp.js` caused all kinds of issues, most notably memory filling up.

The suggested hack fixed that problem for me.

(eventually, I reverted back to `node-xmpp-client` and implemented SCRAM-SHA-1 for it, which was the only reason I initially moved to `xmpp.js`)

**Comment by trampi** [comment] 2018-09-12 12:09
Hi!

I am developing an angular based Chat UI using xmpp.js (see [pazznetwork/ngx-chat](https://github.com/pazznetwork/ngx-chat)).
After reading this issue I tried to reproduce it - without success.

A minimal example that should reproduce it can be found here: https://github.com/trampi/xmppjs-memleak
In my case, it does NOT print a parent for stanzas.

**Comment by Gilead** [comment] 2018-09-12 15:05
A word of warning: if you do
```stanza.parent = null;```
then the history will NOT be cleared as you would only be removing the parent reference from the current stanza object (kind of duh in hindsight). You will see it when a connection status callback comes back; it'll contain the whole history again (I just received one with thousands of entries in it).
My current solution is:
```greedyParent.children.splice(0, greedyParent.children.length);```

@trampi I'm not doing anything special; create a client, set up callbacks, client.start(...) and that's it. No idea why you are not seeing this behaviour. Perhaps you configure the library in some way? Do you have any configuration at all? Considering there is virtually no documentation for xmpp.js I wouldn't be surprised if there was a setting one needs to change to fix this behaviour.

**Comment by robertklep** [comment] 2018-09-12 16:16
@Gilead @trampi it may be related to the transport that's being used. I was using a direct TCP connection to the XMPP server, whereas the minimal example is using WebSockets.

**Comment by trampi** [comment] 2018-09-12 16:17
@Gilead If you don't mind you could have a look at this repository: https://github.com/trampi/xmppjs-memleak. I could not reproduce the memory leak there, using the latest xmpp.js and going as straightforward as I could (copied the code from http://xmppjs.org/client/ and just adding the auth information and a log statement in case the parent stanza is not null).

@robertklep I will try BOSH in a moment

**Comment by robertklep** [comment] 2018-09-12 16:47
@trampi both BOSH and WebSockets are meant for browser use. I think the problem will manifest itself when running in Node.js (using a plain TCP connection).

**Comment by trampi** [comment] 2018-09-12 16:51
@robertklep could be. Unfortunately I do not have time to investigate further at the moment. But it reduces the area to investigate! :-)

**Comment by sonnyp** [comment] 2018-09-15 19:11
I confirm only TCP connection method is affected, on it :)

**Closed as completed** 2018-09-16 11:24 UTC

**Comment by sonnyp** [comment] 2018-09-16 11:45
@robertklep can you share your additional issues with xmpp.js ? I would like to release 1.0 ASAP and any feedback is appreciated.

**Comment by robertklep** [comment] 2018-09-16 11:51
@sonnyp if I could I would have :(

Apart from the memoryleaks, I haven't been able to reproduce the problems that the users of my module ([`nefit-easy-http-server`](https://www.npmjs.com/package/nefit-easy-http-server)) were having, but it roughly comes down to reconnects not working properly and unexplained CPU spikes.

Almost all users with these problems use the module in combination with a home automation platform called Domoticz, which I don't run myself, so it could theoretically be caused by that, but all their problems have disappeared once I reverted back to `node-xmpp-client`.

**Comment by robertklep** [comment] 2018-09-16 14:35
@sonnyp cool, thanks!

Right now I don't have a reason to revert back to `@xmpp/client` because I got SCRAM-SHA-1 working on the older version, but for future projects (or big updates) I'll consider it again :D
